# requires unstable rustfmt until the options are stabilized
unstable_features = true
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
